version: 2

with_node: &with_node
  docker:
    - image: cimg/node:16.15

jobs:
  test:
    docker:
      - image: cimg/node:16.15

    steps:
      - checkout

      - run:
          name: Install Node dependencies
          command: npm ci

      # - run:
      #     name: Run tests
      #     environment:
      #       NODE_CONFIG_ENV: ci
      #     command: npm test

  types:
    <<: *with_node

    steps:
      - checkout

      - run:
          name: Install Node dependencies
          command: npm ci

      - run:
          name: Check lint
          command: npm run check-types

  lint:
    <<: *with_node

    steps:
      - checkout

      - run:
          name: Install Node dependencies
          command: npm ci

      - run:
          name: Check lint
          command: npm run lint

      - run:
          name: Check that package version numbers are in sync
          when: always
          command: npm run check-package-version


  format:
    <<: *with_node

    steps:
      - checkout

      - run:
          name: Install Node dependencies
          command: npm ci

      - run:
          name: Check code format
          command: npm run format:check

workflows:
  version: 2

  on-commit:
    jobs:
      - types
      - test
      - lint
      - format

  daily:
    triggers:
      - schedule:
          cron: '0 17 * * *'
          filters:
            branches:
              only: main
    jobs:
      - types
      - test
      - lint
      - format
